= Trivia Question
ifndef::imagesdir[:imagesdir: images]
:revealjs_theme: solarized
:author: Greg Hutchinson


[transition=slide-in fade-out]
## Trivia Question 
If you were living in Rome at the time, what was the date that followed Thursday October 4, 1582? 
[%step]
* *Hint: Pope Gregory XIII was the pope at that time.* +
* *Hint: Something to do with Leap Years* +



[transition=slide-in fade-out]
## Trivia Question 
If you were living in Rome at the time, what was the date that followed Thursday October 4, 1582? +
 +
 +
[transition=fade-in fade-out]
## Trivia Question
If you were living in Rome at the time, what was the date that followed Thursday October 4, 1582? +
*Hint: Pope Gregory XIII was the pope at that time.* +
 +
[transition=fade-in fade-out]
## Trivia Question
If you were living in Rome at the time, what was the date that followed Thursday October 4, 1582? +
*Hint: Pope Gregory XIII was the pope at that time.* +
*Hint: Something to do with Leap Years* +

## Explanation
[%step]
* Leap years were every 4th year in the Julian Calendar
* This was close but a little inaccurate (~10 mins / year)<br>(~10 mins / year * 1582 years / 1440 mins / day)
* Over 15 centuries it adds up to 10 days
* Vernal equinox was moving into winter, instead of spring
* First Sunday after the first full moon after the vernal equinox which everyone knows better as ...

---?image=assets/img/easter-bunny.png&size=contain

## Easter

## Trivia Question (Explanation)
#### Switched to Gregorian Calendar from Julian
@snap[midpoint text-09 text-left span-100 ]
@ul[list-fade-fragments]
- Fixed the leap year calculation so that it is every 4th but not every 100th unless 400th
- Dropped 10 days from the Calendar to realign Easter
- So - The day after Thursday October 4,1582 was ...
- Friday October 15, 1582
- P.S. - Same thing happened in the US ~200 years later<br>Wednesday, 2 September 1752 was followed by <br>Thursday, 14 September 1752;
@ulend
@snapend
---
